name: ci
on: [push, pull_request]
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.x" }
      - name: Run python projects (non-interactive)
        run: |
          set -e
          for f in $(git ls-files "*/src/main.py"); do
            echo "Smoke: $f"
            printf "rock\nq\n" | python3 "$f" >/dev/null
          done
      - name: Build & run C++ projects (non-interactive)
        run: |
          set -e
          for f in $(git ls-files "*/src/main.cpp"); do
            echo "Build: $f"
            out="/tmp/$(basename $(dirname $(dirname "$f")))"
            g++ -std=c++17 -O2 -Wall -Wextra "$f" -o "$out"
            echo "Smoke: $out"
            printf "50\nq\n" | "$out" >/dev/null
          done
      - name: Install Rust (stable)
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Build & run Rust projects (non-interactive)
        run: |
          set -e
          for f in $(git ls-files "*/src/main.rs"); do
            echo "Build: $f"
            out="/tmp/$(basename $(dirname $(dirname "$f")))"
            rustc "$f" -O -o "$out"
            printf "h\nq\n" | "$out" >/dev/null
          done
          - uses: actions/setup-go@v5
        with:
          go-version: "1.x"

      - name: Build & run Go projects (non-interactive)
        run: |
          set -e
          for f in $(git ls-files "*/src/main.go"); do
            echo "Build: $f"
            out="/tmp/$(basename $(dirname $(dirname "$f")))"
            go build -o "$out" "$f"
            printf "e\nq\n" | "$out" >/dev/null
          done